# Generated by Django 6.1.dev20260519043807 on 2026-05-30 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='learninglog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learning_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=160)),
                ('summary', models.TextField()),
                ('explanation', models.TextField()),
                ('source_file', models.CharField(max_length=220)),
                ('source_symbol', models.CharField(blank=True, max_length=120)),
                ('reading_order', models.PositiveSmallIntegerField(default=0)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='learning.topic')),
            ],
            options={
                'ordering': ['topic__reading_order', 'reading_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='LessonStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=160)),
                ('body', models.TextField()),
                ('action', models.TextField()),
                ('checkpoint', models.TextField()),
                ('source_file', models.CharField(max_length=220)),
                ('source_symbol', models.CharField(blank=True, max_length=120)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='learning.lesson')),
            ],
            options={
                'ordering': ['lesson__reading_order', 'order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='exercise',
            name='lesson_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='learning.lessonstep'),
        ),
        migrations.CreateModel(
            name='MiniProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=160)),
                ('summary', models.TextField()),
                ('objective', models.TextField()),
                ('source_file', models.CharField(max_length=220)),
                ('source_symbol', models.CharField(blank=True, max_length=120)),
                ('reading_order', models.PositiveSmallIntegerField(default=0)),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='learning.topic')),
            ],
            options={
                'ordering': ['reading_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=160)),
                ('prompt', models.TextField()),
                ('source_hint', models.CharField(blank=True, max_length=220)),
                ('next_action', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='learning.miniproject')),
            ],
            options={
                'ordering': ['project__reading_order', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTaskProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='learning.projecttask')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StepProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='learning.lessonstep')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('todo', 'Todo'), ('doing', 'Doing'), ('done', 'Done')], default='todo', max_length=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='learning.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'exercise'), name='unique_exercise_progress_per_user')],
            },
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('topic', 'slug'), name='unique_lesson_slug_per_topic'),
        ),
        migrations.AddConstraint(
            model_name='lessonstep',
            constraint=models.UniqueConstraint(fields=('lesson', 'slug'), name='unique_step_slug_per_lesson'),
        ),
        migrations.AddConstraint(
            model_name='projecttask',
            constraint=models.UniqueConstraint(fields=('project', 'slug'), name='unique_task_slug_per_project'),
        ),
        migrations.AddConstraint(
            model_name='projecttaskprogress',
            constraint=models.UniqueConstraint(fields=('user', 'task'), name='unique_project_task_progress_per_user'),
        ),
        migrations.AddConstraint(
            model_name='stepprogress',
            constraint=models.UniqueConstraint(fields=('user', 'step'), name='unique_step_progress_per_user'),
        ),
    ]
